imports:
    - { resource: config.yml }

# In production environment you should know that the parameters for URL generation
# always pass the requirements. Otherwise it would break your link (or even site with
# strict_requirements = true). So we can disable the requirements check completely for
# enhanced performance with strict_requirements = null.
framework:
    router:
        strict_requirements: null
    #validation:
    #    cache: apc

#doctrine:
#    orm:
#        metadata_cache_driver: apc
#        result_cache_driver: apc
#        query_cache_driver: apc

monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: error
            handler:      nested
        nested:
            type:  stream
            path:  %kernel.logs_dir%/%kernel.environment%.log
            level: debug
    
nelmio_security:
    # prevents framing of the entire site
#    clickjacking:
#        paths:
#            '^/.*': DENY
    # prevents redirections outside the website's domain
#    external_redirects:
#        abort: true
#        log: true
    # forced HTTPS handling, don't combine with flexible mode
    # and make sure you have SSL working on your site before enabling this
#    forced_ssl: 
#        enabled: true
#        hsts_max_age: 2592000 # 30 days
#        hsts_subdomains: true