security:
    encoders:
        INTI\RegistroAcademicoBundle\Entity\Usuario:
            algorithm: sha512
            encode-as-base64: true
            iterations: 10

    role_hierarchy:
        ROLE_ACADEMIC:       ROLE_USER
        ROLE_ACADEMIC_ADMIN: ROLE_ACADEMIC
        ROLE_ADMIN:          ROLE_USER
        ROLE_SERV_SOC:       ROLE_USER
        ROLE_PRAC_PROF:      ROLE_USER
        ROLE_SUPER_ADMIN:    [ROLE_USER, ROLE_ADMIN, ROLE_ACADEMIC_ADMIN, ROLE_SERV_SOC, ROLE_PRAC_PROF ROLE_ALLOWED_TO_SWITCH]

    providers:
        user_db:
            entity:
                class: RegistroAcademicoBundle:Usuario
                property: username

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern: ^/login$
            security: false

        #web_service:
        #    pattern: ^/ws
        #    security: true
        #    http_basic:
        #        realm: "Introduzca usuario y contraseña"

        main:
            pattern: ^/
            provider: user_db
            form_login:
                login_path: /login
                check_path: /login_check
                default_target_path: index
                remember_me: true
            logout:
                path: /logout
                target: index
            remember_me:
                key: a24d680e112b289c1d408fd351e8abadd4591f6d362675dfc3e6d6ebf6532a25
                lifetime: 1800
                path: ^/
                domain: ~
            security: true
            anonymous: ~

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/user, roles: ROLE_USER }
        - { path: ^/expediente, roles: ROLE_USER }
        - { path: ^/aspirante, roles: ROLE_ACADEMIC }
        - { path: ^/materia, roles: ROLE_ACADEMIC }
        - { path: ^/especialidad, roles: ROLE_ACADEMIC_ADMIN }
        - { path: ^/empleado, roles: ROLE_ADMIN }
        - { path: ^/, roles: IS_AUTHENTICATED_FULLY }
        #- { path: ^/, roles: IS_AUTHENTICATED_FULLY, requires_channel: https }
