# src/INTI/RegistroAcademicoBundle/Resources/config/services.yml
services:
    # the menu builder service. Can be used for several menus
    registro_academico.menu_builder:
        class: INTI\RegistroAcademicoBundle\Menu\MenuBuilder
        arguments: ["@knp_menu.factory"]

    # your menu
    registro_academico.menu.breadcrumb:
        class: Knp\Menu\MenuItem
        factory_service: registro_academico.menu_builder # the menu builder service above
        factory_method: createBreadcrumbMenu # the method name to generate the menu
        arguments: ["@request"]
        scope: request
        tags:
            - { name: knp_menu.menu, alias: breadcrumb } # The alias is used in the template
