<?php

namespace INTI\RegistroAcademicoBundle\Repository;

use Doctrine\ORM\EntityRepository;
use INTI\RegistroAcademicoBundle\Entity\Especialidad;
use INTI\RegistroAcademicoBundle\Entity\Empleado;

/**
 * CodigoEspecialidadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CodigoEspecialidadRepository extends EntityRepository {
	/**
	 * Buscar codigos por especialidad
	 *
	 * @param  Especialidad $especialidad
	 * @return array
	 */
	public function findByEspecialidad(Especialidad $especialidad)
	{
		$query = $this->getEntityManager()
				->createQuery("SELECT cod FROM RegistroAcademicoBundle:CodigoEspecialidad cod WHERE cod.especialidad = :especialidad")
				->setParameter(':especialidad', $especialidad->getCodigo());
		return $query->getResult();
	}

	public function findByResponsable(Empleado $responsable)
	{
		$query = $this->getEntityManager()
				->createQuery("SELECT cod FROM RegistroAcademicoBundle:CodigoEspecialidad cod WHERE cod.especialidad IN (SELECT em.responsabilidad FROM RegistroAcademicoBundle:Empleado em WHERE em.dui = :dui)")
				->setParameter(':dui', $responsable->getDui());
		return $query->getResult();

	}
}